// Comprehensive chip data for Ruby's Gifts questionnaire
// Each question has 50+ options with Phosphor icons for enhanced UX

const CHIP_DATA = {
  // Question 1: What do you call them?
  nicknames: [
    { text: "buddy", icon: "ph ph-user" },
    { text: "sweetheart", icon: "ph ph-heart" },
    { text: "bro", icon: "ph ph-handshake" },
    { text: "sis", icon: "ph ph-users" },
    { text: "babe", icon: "ph ph-heart-straight" },
    { text: "honey", icon: "ph ph-drop" },
    { text: "love", icon: "ph ph-heart-break" },
    { text: "darling", icon: "ph ph-sparkle" },
    { text: "baby", icon: "ph ph-baby" },
    { text: "angel", icon: "ph ph-wings" },
    { text: "sunshine", icon: "ph ph-sun" },
    { text: "pumpkin", icon: "ph ph-pumpkin" },
    { text: "buttercup", icon: "ph ph-flower" },
    { text: "princess", icon: "ph ph-crown" },
    { text: "prince", icon: "ph ph-crown-simple" },
    { text: "champ", icon: "ph ph-trophy" },
    { text: "kiddo", icon: "ph ph-smiley" },
    { text: "sport", icon: "ph ph-soccer-ball" },
    { text: "tiger", icon: "ph ph-cat" },
    { text: "bear", icon: "ph ph-teddy-bear" },
    { text: "monkey", icon: "ph ph-tree-palm" },
    { text: "bunny", icon: "ph ph-rabbit" },
    { text: "duck", icon: "ph ph-bird" },
    { text: "munchkin", icon: "ph ph-cookie" },
    { text: "snuggle bug", icon: "ph ph-bug" },
    { text: "cupcake", icon: "ph ph-cake" },
    { text: "cookie", icon: "ph ph-cookie" },
    { text: "cutie pie", icon: "ph ph-pie-chart" },
    { text: "smarty pants", icon: "ph ph-graduation-cap" },
    { text: "trouble", icon: "ph ph-warning" },
    { text: "goofball", icon: "ph ph-smiley-wink" },
    { text: "rockstar", icon: "ph ph-microphone-stage" },
    { text: "superstar", icon: "ph ph-star" },
    { text: "champion", icon: "ph ph-medal" },
    { text: "genius", icon: "ph ph-brain" },
    { text: "wizard", icon: "ph ph-magic-wand" },
    { text: "ninja", icon: "ph ph-sword" },
    { text: "captain", icon: "ph ph-anchor" },
    { text: "chief", icon: "ph ph-crown" },
    { text: "boss", icon: "ph ph-briefcase" },
    { text: "dude", icon: "ph ph-person" },
    { text: "mate", icon: "ph ph-handshake" },
    { text: "pal", icon: "ph ph-users-three" },
    { text: "amigo", icon: "ph ph-house" },
    { text: "compadre", icon: "ph ph-cowboy-hat" },
    { text: "bestie", icon: "ph ph-heart-straight" },
    { text: "partner", icon: "ph ph-handshake" },
    { text: "sidekick", icon: "ph ph-users" },
    { text: "wingman", icon: "ph ph-airplane" },
    { text: "loro", icon: "ph ph-chat-circle" },
    { text: "querido", icon: "ph ph-heart" },
    { text: "cariño", icon: "ph ph-heart-straight" },
    { text: "mi amor", icon: "ph ph-heart-break" },
    { text: "tesoro", icon: "ph ph-treasure-chest" },
    { text: "corazón", icon: "ph ph-heart" }
  ],

  // Question 2: What's your relationship?
  relationships: [
    { text: "best friend", icon: "ph ph-star" },
    { text: "sibling", icon: "ph ph-users" },
    { text: "crush", icon: "ph ph-flame" },
    { text: "boyfriend", icon: "ph ph-heart" },
    { text: "girlfriend", icon: "ph ph-heart-straight" },
    { text: "spouse", icon: "ph ph-rings" },
    { text: "partner", icon: "ph ph-handshake" },
    { text: "parent", icon: "ph ph-house" },
    { text: "child", icon: "ph ph-baby" },
    { text: "grandparent", icon: "ph ph-tree" },
    { text: "grandchild", icon: "ph ph-flower" },
    { text: "cousin", icon: "ph ph-users-three" },
    { text: "aunt", icon: "ph ph-user" },
    { text: "uncle", icon: "ph ph-user" },
    { text: "nephew", icon: "ph ph-person" },
    { text: "niece", icon: "ph ph-person" },
    { text: "work buddy", icon: "ph ph-briefcase" },
    { text: "colleague", icon: "ph ph-buildings" },
    { text: "boss", icon: "ph ph-crown" },
    { text: "employee", icon: "ph ph-id-card" },
    { text: "mentor", icon: "ph ph-graduation-cap" },
    { text: "student", icon: "ph ph-student" },
    { text: "teacher", icon: "ph ph-chalkboard-teacher" },
    { text: "classmate", icon: "ph ph-users" },
    { text: "roommate", icon: "ph ph-house" },
    { text: "neighbor", icon: "ph ph-house-line" },
    { text: "ex-partner", icon: "ph ph-heart-break" },
    { text: "friend with benefits", icon: "ph ph-smiley-wink" },
    { text: "acquaintance", icon: "ph ph-handshake" },
    { text: "distant friend", icon: "ph ph-map-pin" },
    { text: "childhood friend", icon: "ph ph-baby-carriage" },
    { text: "online friend", icon: "ph ph-globe" },
    { text: "gym buddy", icon: "ph ph-barbell" },
    { text: "travel companion", icon: "ph ph-airplane" },
    { text: "study partner", icon: "ph ph-books" },
    { text: "gaming friend", icon: "ph ph-game-controller" },
    { text: "drinking buddy", icon: "ph ph-wine" },
    { text: "business partner", icon: "ph ph-handshake" },
    { text: "creative collaborator", icon: "ph ph-palette" },
    { text: "workout partner", icon: "ph ph-person-arms-spread" },
    { text: "dance partner", icon: "ph ph-music-notes" },
    { text: "cooking buddy", icon: "ph ph-chef-hat" },
    { text: "book club friend", icon: "ph ph-book-open" },
    { text: "hiking companion", icon: "ph ph-mountains" },
    { text: "shopping buddy", icon: "ph ph-shopping-bag" },
    { text: "movie buddy", icon: "ph ph-film-strip" },
    { text: "concert buddy", icon: "ph ph-microphone-stage" },
    { text: "food buddy", icon: "ph ph-fork-knife" },
    { text: "adventure partner", icon: "ph ph-compass" },
    { text: "soul mate", icon: "ph ph-infinity" },
    { text: "life partner", icon: "ph ph-heart-straight" },
    { text: "family friend", icon: "ph ph-house-simple" },
    { text: "pen pal", icon: "ph ph-envelope" },
    { text: "frenemy", icon: "ph ph-mask-sad" },
    { text: "secret admirer", icon: "ph ph-eye-closed" }
  ],

  // Question 3: What have you already gifted them?
  previousGifts: [
    { text: "chocolate", icon: "ph ph-cake" },
    { text: "book", icon: "ph ph-book" },
    { text: "jewelry", icon: "ph ph-diamond" },
    { text: "flowers", icon: "ph ph-flower" },
    { text: "perfume", icon: "ph ph-drop" },
    { text: "watch", icon: "ph ph-clock" },
    { text: "clothing", icon: "ph ph-t-shirt" },
    { text: "shoes", icon: "ph ph-sneaker" },
    { text: "handbag", icon: "ph ph-handbag" },
    { text: "wallet", icon: "ph ph-wallet" },
    { text: "phone case", icon: "ph ph-device-mobile" },
    { text: "headphones", icon: "ph ph-headphones" },
    { text: "speaker", icon: "ph ph-speaker-high" },
    { text: "gaming console", icon: "ph ph-game-controller" },
    { text: "laptop", icon: "ph ph-laptop" },
    { text: "tablet", icon: "ph ph-device-tablet" },
    { text: "camera", icon: "ph ph-camera" },
    { text: "fitness tracker", icon: "ph ph-heart-rate" },
    { text: "coffee mug", icon: "ph ph-coffee" },
    { text: "wine", icon: "ph ph-wine" },
    { text: "candles", icon: "ph ph-candle" },
    { text: "artwork", icon: "ph ph-palette" },
    { text: "plant", icon: "ph ph-plant" },
    { text: "home decor", icon: "ph ph-house" },
    { text: "kitchen gadget", icon: "ph ph-chef-hat" },
    { text: "board game", icon: "ph ph-game-controller" },
    { text: "puzzle", icon: "ph ph-puzzle-piece" },
    { text: "subscription box", icon: "ph ph-package" },
    { text: "gift card", icon: "ph ph-credit-card" },
    { text: "concert tickets", icon: "ph ph-ticket" },
    { text: "movie tickets", icon: "ph ph-film-strip" },
    { text: "spa voucher", icon: "ph ph-flower-lotus" },
    { text: "restaurant voucher", icon: "ph ph-fork-knife" },
    { text: "vacation trip", icon: "ph ph-airplane" },
    { text: "experience day", icon: "ph ph-calendar" },
    { text: "cooking class", icon: "ph ph-chef-hat" },
    { text: "gym membership", icon: "ph ph-barbell" },
    { text: "massage", icon: "ph ph-hands-praying" },
    { text: "manicure", icon: "ph ph-hand" },
    { text: "haircut", icon: "ph ph-scissors" },
    { text: "makeup", icon: "ph ph-eyedropper" },
    { text: "skincare", icon: "ph ph-drop" },
    { text: "vitamins", icon: "ph ph-pill" },
    { text: "tea set", icon: "ph ph-coffee" },
    { text: "photo album", icon: "ph ph-camera" },
    { text: "custom portrait", icon: "ph ph-user-circle" },
    { text: "handmade craft", icon: "ph ph-hands-praying" },
    { text: "baked goods", icon: "ph ph-cookie" },
    { text: "homemade meal", icon: "ph ph-fork-knife" },
    { text: "playlist", icon: "ph ph-music-notes" },
    { text: "poem", icon: "ph ph-scroll" },
    { text: "love letter", icon: "ph ph-envelope-simple" },
    { text: "nothing yet", icon: "ph ph-x-circle" },
    { text: "surprise party", icon: "ph ph-party-popper" },
    { text: "picnic", icon: "ph ph-basket" }
  ],

  // Question 4: What will they absolutely hate?
  dislikes: [
    { text: "spiders", icon: "ph ph-bug" },
    { text: "loud noises", icon: "ph ph-speaker-x" },
    { text: "cheap plastic", icon: "ph ph-trash" },
    { text: "clutter", icon: "ph ph-stack" },
    { text: "bad smells", icon: "ph ph-nose" },
    { text: "crowded places", icon: "ph ph-users-four" },
    { text: "early mornings", icon: "ph ph-clock" },
    { text: "horror movies", icon: "ph ph-ghost" },
    { text: "spicy food", icon: "ph ph-fire" },
    { text: "cold weather", icon: "ph ph-snowflake" },
    { text: "hot weather", icon: "ph ph-thermometer-hot" },
    { text: "rain", icon: "ph ph-cloud-rain" },
    { text: "snow", icon: "ph ph-snowflake" },
    { text: "bugs", icon: "ph ph-bug-beetle" },
    { text: "snakes", icon: "ph ph-snake" },
    { text: "heights", icon: "ph ph-mountains" },
    { text: "small spaces", icon: "ph ph-square" },
    { text: "public speaking", icon: "ph ph-microphone" },
    { text: "driving", icon: "ph ph-car" },
    { text: "flying", icon: "ph ph-airplane" },
    { text: "needles", icon: "ph ph-syringe" },
    { text: "blood", icon: "ph ph-drop" },
    { text: "dentist", icon: "ph ph-tooth" },
    { text: "hospitals", icon: "ph ph-hospital" },
    { text: "exercising", icon: "ph ph-barbell" },
    { text: "dieting", icon: "ph ph-apple-logo" },
    { text: "cleaning", icon: "ph ph-broom" },
    { text: "cooking", icon: "ph ph-chef-hat" },
    { text: "shopping", icon: "ph ph-shopping-cart" },
    { text: "crowds", icon: "ph ph-users" },
    { text: "parties", icon: "ph ph-party-popper" },
    { text: "social events", icon: "ph ph-champagne" },
    { text: "small talk", icon: "ph ph-chat-circle" },
    { text: "waiting", icon: "ph ph-hourglass" },
    { text: "being late", icon: "ph ph-clock" },
    { text: "traffic", icon: "ph ph-traffic-cone" },
    { text: "technology", icon: "ph ph-robot" },
    { text: "social media", icon: "ph ph-share-network" },
    { text: "texting", icon: "ph ph-chat-text" },
    { text: "phone calls", icon: "ph ph-phone" },
    { text: "video calls", icon: "ph ph-video-camera" },
    { text: "cats", icon: "ph ph-cat" },
    { text: "dogs", icon: "ph ph-dog" },
    { text: "pets", icon: "ph ph-paw-print" },
    { text: "children", icon: "ph ph-baby" },
    { text: "babies crying", icon: "ph ph-baby-carriage" },
    { text: "loud music", icon: "ph ph-speaker-high" },
    { text: "country music", icon: "ph ph-cowboy-hat" },
    { text: "pop music", icon: "ph ph-music-notes" },
    { text: "classical music", icon: "ph ph-violin" },
    { text: "jazz music", icon: "ph ph-music-note" },
    { text: "reality TV", icon: "ph ph-television" },
    { text: "sports", icon: "ph ph-soccer-ball" },
    { text: "news", icon: "ph ph-newspaper" },
    { text: "politics", icon: "ph ph-megaphone" }
  ],

  // Question 5: What do they keep complaining about?
  complaints: [
    { text: "traffic", icon: "ph ph-car" },
    { text: "work stress", icon: "ph ph-briefcase" },
    { text: "bad weather", icon: "ph ph-cloud" },
    { text: "long lines", icon: "ph ph-queue" },
    { text: "slow internet", icon: "ph ph-wifi-x" },
    { text: "phone battery dying", icon: "ph ph-battery-empty" },
    { text: "expensive prices", icon: "ph ph-money" },
    { text: "bad service", icon: "ph ph-thumbs-down" },
    { text: "noisy neighbors", icon: "ph ph-speaker-high" },
    { text: "messy roommates", icon: "ph ph-broom" },
    { text: "back pain", icon: "ph ph-person" },
    { text: "headaches", icon: "ph ph-head-circuit" },
    { text: "insomnia", icon: "ph ph-moon" },
    { text: "tiredness", icon: "ph ph-bed" },
    { text: "weight gain", icon: "ph ph-scale" },
    { text: "hair loss", icon: "ph ph-scissors" },
    { text: "dry skin", icon: "ph ph-drop" },
    { text: "allergies", icon: "ph ph-sneeze" },
    { text: "cold symptoms", icon: "ph ph-thermometer" },
    { text: "stomach issues", icon: "ph ph-pills" },
    { text: "bad food", icon: "ph ph-fork-knife" },
    { text: "cold coffee", icon: "ph ph-coffee" },
    { text: "warm beer", icon: "ph ph-beer-bottle" },
    { text: "melted ice cream", icon: "ph ph-ice-cream" },
    { text: "burnt toast", icon: "ph ph-fire" },
    { text: "soggy cereal", icon: "ph ph-bowl-food" },
    { text: "flat soda", icon: "ph ph-soda-bottle" },
    { text: "stale bread", icon: "ph ph-bread" },
    { text: "overcooked pasta", icon: "ph ph-fork-knife" },
    { text: "undercooked meat", icon: "ph ph-cooking-pot" },
    { text: "too much salt", icon: "ph ph-drop" },
    { text: "no seasoning", icon: "ph ph-pepper" },
    { text: "long commute", icon: "ph ph-train" },
    { text: "parking issues", icon: "ph ph-car" },
    { text: "gas prices", icon: "ph ph-gas-pump" },
    { text: "public transport", icon: "ph ph-bus" },
    { text: "flight delays", icon: "ph ph-airplane" },
    { text: "lost luggage", icon: "ph ph-suitcase" },
    { text: "hotel rooms", icon: "ph ph-bed" },
    { text: "tourist traps", icon: "ph ph-camera" },
    { text: "work meetings", icon: "ph ph-users-four" },
    { text: "deadlines", icon: "ph ph-calendar-x" },
    { text: "overtime", icon: "ph ph-clock" },
    { text: "micromanaging boss", icon: "ph ph-eye" },
    { text: "difficult clients", icon: "ph ph-phone-x" },
    { text: "office temperature", icon: "ph ph-thermometer" },
    { text: "broken printer", icon: "ph ph-printer" },
    { text: "slow computer", icon: "ph ph-laptop" },
    { text: "software bugs", icon: "ph ph-bug" },
    { text: "spam emails", icon: "ph ph-envelope-x" },
    { text: "social media drama", icon: "ph ph-warning" },
    { text: "fake news", icon: "ph ph-newspaper" },
    { text: "clickbait", icon: "ph ph-mouse-left-click" },
    { text: "auto-play videos", icon: "ph ph-play" },
    { text: "pop-up ads", icon: "ph ph-x-square" }
  ],

  // Question 6: How would you complain about them?
  quirks: [
    { text: "always late", icon: "ph ph-clock" },
    { text: "too picky", icon: "ph ph-magnifying-glass" },
    { text: "loud chewer", icon: "ph ph-mouth" },
    { text: "never listens", icon: "ph ph-ear-slash" },
    { text: "talks too much", icon: "ph ph-chat-circle" },
    { text: "interrupts constantly", icon: "ph ph-hand-pointing" },
    { text: "leaves messes", icon: "ph ph-broom" },
    { text: "forgets everything", icon: "ph ph-brain" },
    { text: "procrastinates", icon: "ph ph-hourglass" },
    { text: "perfectionist", icon: "ph ph-star" },
    { text: "control freak", icon: "ph ph-steering-wheel" },
    { text: "drama queen", icon: "ph ph-theater-masks" },
    { text: "attention seeker", icon: "ph ph-eye" },
    { text: "know-it-all", icon: "ph ph-graduation-cap" },
    { text: "stubborn", icon: "ph ph-wall" },
    { text: "moody", icon: "ph ph-mood-sad" },
    { text: "jealous", icon: "ph ph-eye-closed" },
    { text: "clingy", icon: "ph ph-hands-clapping" },
    { text: "flaky", icon: "ph ph-snowflake" },
    { text: "unreliable", icon: "ph ph-x-circle" },
    { text: "overshares", icon: "ph ph-share-network" },
    { text: "gossips", icon: "ph ph-chat-circle-dots" },
    { text: "judges others", icon: "ph ph-scales" },
    { text: "pessimistic", icon: "ph ph-cloud-rain" },
    { text: "complains constantly", icon: "ph ph-minus-circle" },
    { text: "never satisfied", icon: "ph ph-thumbs-down" },
    { text: "indecisive", icon: "ph ph-question" },
    { text: "overthinks", icon: "ph ph-brain" },
    { text: "anxious", icon: "ph ph-warning-circle" },
    { text: "workaholic", icon: "ph ph-briefcase" },
    { text: "lazy", icon: "ph ph-bed" },
    { text: "messy eater", icon: "ph ph-fork-knife" },
    { text: "bad driver", icon: "ph ph-car" },
    { text: "road rage", icon: "ph ph-warning" },
    { text: "sore loser", icon: "ph ph-trophy" },
    { text: "cheats at games", icon: "ph ph-game-controller" },
    { text: "hogs the remote", icon: "ph ph-television" },
    { text: "channel surfer", icon: "ph ph-arrows-clockwise" },
    { text: "spoils movies", icon: "ph ph-film-strip" },
    { text: "reads endings first", icon: "ph ph-book-open" },
    { text: "leaves lights on", icon: "ph ph-lightbulb" },
    { text: "wastes water", icon: "ph ph-drop" },
    { text: "throws away food", icon: "ph ph-trash" },
    { text: "hoards things", icon: "ph ph-stack" },
    { text: "impulse buyer", icon: "ph ph-credit-card" },
    { text: "penny pincher", icon: "ph ph-coins" },
    { text: "bad with money", icon: "ph ph-money" },
    { text: "forgets anniversaries", icon: "ph ph-calendar" },
    { text: "bad gift giver", icon: "ph ph-gift" },
    { text: "doesn't text back", icon: "ph ph-chat-text" },
    { text: "leaves on read", icon: "ph ph-check" },
    { text: "social media addict", icon: "ph ph-device-mobile" },
    { text: "takes forever to reply", icon: "ph ph-hourglass" },
    { text: "sends voice messages", icon: "ph ph-microphone" },
    { text: "calls instead of texting", icon: "ph ph-phone" }
  ],

  // Question 7: What's your budget?
  budget: [
    { text: "under ₹200", icon: "ph ph-coin" },
    { text: "₹200-500", icon: "ph ph-coins" },
    { text: "₹500-1000", icon: "ph ph-money" },
    { text: "₹1000-2000", icon: "ph ph-currency-dollar" },
    { text: "₹2000-5000", icon: "ph ph-credit-card" },
    { text: "₹5000-10000", icon: "ph ph-bank" },
    { text: "₹10000-20000", icon: "ph ph-currency-circle-dollar" },
    { text: "₹20000-50000", icon: "ph ph-treasure-chest" },
    { text: "above ₹50000", icon: "ph ph-diamond" },
    { text: "luxury splurge", icon: "ph ph-crown" },
    { text: "money is no object", icon: "ph ph-infinity" },
    { text: "as cheap as possible", icon: "ph ph-piggy-bank" },
    { text: "mid-range", icon: "ph ph-scales" },
    { text: "premium quality", icon: "ph ph-medal" },
    { text: "budget-friendly", icon: "ph ph-thumbs-up" },
    { text: "value for money", icon: "ph ph-star" },
    { text: "splurge for special occasion", icon: "ph ph-party-popper" },
    { text: "gift card amount", icon: "ph ph-credit-card" },
    { text: "what I spent on myself", icon: "ph ph-user-circle" },
    { text: "same as last gift", icon: "ph ph-equals" },
    { text: "double last gift", icon: "ph ph-plus-circle" },
    { text: "half of last gift", icon: "ph ph-minus-circle" },
    { text: "group gift contribution", icon: "ph ph-users" },
    { text: "secret santa limit", icon: "ph ph-gift" },
    { text: "birthday budget", icon: "ph ph-cake" },
    { text: "anniversary budget", icon: "ph ph-heart" },
    { text: "holiday budget", icon: "ph ph-snowflake" },
    { text: "graduation budget", icon: "ph ph-graduation-cap" },
    { text: "wedding gift budget", icon: "ph ph-rings" },
    { text: "housewarming budget", icon: "ph ph-house" },
    { text: "baby shower budget", icon: "ph ph-baby" },
    { text: "retirement budget", icon: "ph ph-clock" },
    { text: "just because budget", icon: "ph ph-smiley" },
    { text: "apology gift budget", icon: "ph ph-heart-break" },
    { text: "thank you gift budget", icon: "ph ph-hands-praying" },
    { text: "congratulations budget", icon: "ph ph-trophy" },
    { text: "get well soon budget", icon: "ph ph-first-aid" },
    { text: "sympathy gift budget", icon: "ph ph-flower-lotus" },
    { text: "welcome gift budget", icon: "ph ph-door-open" },
    { text: "farewell gift budget", icon: "ph ph-wave" },
    { text: "promotion gift budget", icon: "ph ph-trend-up" },
    { text: "new job gift budget", icon: "ph ph-briefcase-simple" },
    { text: "achievement gift budget", icon: "ph ph-medal-military" },
    { text: "milestone birthday budget", icon: "ph ph-number-circle-one" },
    { text: "first date budget", icon: "ph ph-heart-straight" },
    { text: "valentine's day budget", icon: "ph ph-heart" },
    { text: "mother's day budget", icon: "ph ph-flower" },
    { text: "father's day budget", icon: "ph ph-necktie" },
    { text: "friendship day budget", icon: "ph ph-handshake" },
    { text: "teacher's day budget", icon: "ph ph-chalkboard-teacher" },
    { text: "boss's day budget", icon: "ph ph-crown-simple" },
    { text: "employee appreciation budget", icon: "ph ph-trophy" },
    { text: "client gift budget", icon: "ph ph-handshake" },
    { text: "hostess gift budget", icon: "ph ph-house-simple" },
    { text: "dinner party gift budget", icon: "ph ph-wine" }
  ],

  // Question 8: Any other limitations?
  limitations: [
    { text: "allergy-free", icon: "ph ph-shield" },
    { text: "eco-friendly", icon: "ph ph-leaf" },
    { text: "portable", icon: "ph ph-backpack" },
    { text: "small size", icon: "ph ph-resize" },
    { text: "large size", icon: "ph ph-arrows-out" },
    { text: "lightweight", icon: "ph ph-feather" },
    { text: "durable", icon: "ph ph-shield-check" },
    { text: "fragile okay", icon: "ph ph-package" },
    { text: "no fragile items", icon: "ph ph-warning" },
    { text: "easy to wrap", icon: "ph ph-gift" },
    { text: "no wrapping needed", icon: "ph ph-x-circle" },
    { text: "instant delivery", icon: "ph ph-lightning" },
    { text: "same day delivery", icon: "ph ph-clock" },
    { text: "can wait for shipping", icon: "ph ph-hourglass" },
    { text: "local stores only", icon: "ph ph-storefront" },
    { text: "online shopping okay", icon: "ph ph-shopping-cart" },
    { text: "handmade preferred", icon: "ph ph-hands-praying" },
    { text: "brand name important", icon: "ph ph-crown" },
    { text: "generic brands okay", icon: "ph ph-tag" },
    { text: "personalized", icon: "ph ph-user-circle" },
    { text: "no personalization", icon: "ph ph-x" },
    { text: "practical gifts only", icon: "ph ph-wrench" },
    { text: "fun gifts only", icon: "ph ph-smiley" },
    { text: "educational", icon: "ph ph-graduation-cap" },
    { text: "entertaining", icon: "ph ph-television" },
    { text: "useful for daily life", icon: "ph ph-house" },
    { text: "hobby-related", icon: "ph ph-palette" },
    { text: "work-related", icon: "ph ph-briefcase" },
    { text: "health-related", icon: "ph ph-heart-rate" },
    { text: "fitness-related", icon: "ph ph-barbell" },
    { text: "beauty-related", icon: "ph ph-sparkle" },
    { text: "fashion-related", icon: "ph ph-t-shirt" },
    { text: "tech-related", icon: "ph ph-laptop" },
    { text: "book-related", icon: "ph ph-book" },
    { text: "music-related", icon: "ph ph-music-notes" },
    { text: "art-related", icon: "ph ph-palette" },
    { text: "cooking-related", icon: "ph ph-chef-hat" },
    { text: "travel-related", icon: "ph ph-airplane" },
    { text: "pet-related", icon: "ph ph-paw-print" },
    { text: "plant-related", icon: "ph ph-plant" },
    { text: "home decor", icon: "ph ph-house-simple" },
    { text: "office supplies", icon: "ph ph-briefcase" },
    { text: "spiritual/religious", icon: "ph ph-infinity" },
    { text: "cultural", icon: "ph ph-globe" },
    { text: "seasonal", icon: "ph ph-snowflake" },
    { text: "timeless", icon: "ph ph-clock" },
    { text: "trendy", icon: "ph ph-trend-up" },
    { text: "classic", icon: "ph ph-crown-simple" },
    { text: "modern", icon: "ph ph-lightning" },
    { text: "vintage", icon: "ph ph-clock-clockwise" },
    { text: "minimalist", icon: "ph ph-minus" },
    { text: "maximalist", icon: "ph ph-plus" },
    { text: "colorful", icon: "ph ph-palette" },
    { text: "neutral colors", icon: "ph ph-circle" },
    { text: "matching their style", icon: "ph ph-t-shirt" },
    { text: "something different", icon: "ph ph-sparkle" }
  ]
};

// Export for use in main application
if (typeof module !== 'undefined' && module.exports) {
  module.exports = CHIP_DATA;
}